@baseUrl = https://localhost:5151

### Get OpenAPI documentation
GET {{baseUrl}}/openapi.json
Accept: application/json

### Get Swagger UI
GET {{baseUrl}}/swagger
Accept: text/html

### Get base url
GET {{baseUrl}}
Accept: application/json

### Get weather forecast for default 5 days
GET {{baseUrl}}/weatherforecast
Accept: application/json

### Get weather forecast for 3 days
GET {{baseUrl}}/weatherforecast/3
Accept: application/json

### Get weather forecast for 7 days
GET {{baseUrl}}/weatherforecast/7
Accept: application/json


