### Test root page (HTTP)
GET http://localhost:5130/

### Test root page (HTTPS)
GET https://localhost:5131/

### Test welcome page (HTTP)
GET http://localhost:5130/welcome

### Test welcome page (HTTPS)
GET https://localhost:5131/welcome

### Test data endpoint (HTTP)
GET http://localhost:5130/data

### Test data endpoint (HTTPS)
GET https://localhost:5131/data

### Test environment info (HTTP)
GET http://localhost:5130/env

### Test environment info (HTTPS)
GET https://localhost:5131/env

### Test about page (HTTP)
GET http://localhost:5130/about.html

### Test about page (HTTPS)
GET https://localhost:5131/about.html

### Test CSS file (HTTP)
GET http://localhost:5130/site.css

### Test CSS file (HTTPS)
GET https://localhost:5131/site.css 